services:
  api-rest:
    build: ./api-rest
    container_name: api-rest
    networks:
      - my-network
    ports:
      - "3000:3000"

  web-app:
    build: ./web-app
    container_name: web-app
    ports:
      - "8080:8080"
    networks:
      - my-network
    depends_on:
      - api-rest

networks:
  my-network:
    driver: bridge
